apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cicd
  namespace: default
  labels:
    app: test-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-cicd
  template:
    metadata:
      labels:
        app: test-cicd
    spec:
      containers:
        - name: test-cicd
          image: npinkam/test-cicd:latest
          ports:
            - containerPort: 80
              name: http