apiVersion: v1
kind: Service
metadata:
  name: test-cicd
  namespace: default
  labels:
    app: test-cicd
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: test-cicd